<?xml version="1.0" encoding="UTF-8"?>

<!--Autogenerated by Cloudera Manager-->
<configuration>
    <property>
        <name>dfs.nameservices</name>
        <value>data2,flink-2,pub1,rt2</value>
        <final>true</final>
    </property>
    <property>
        <name>dfs.ha.namenodes.data2</name>
        <value>nn1,nn2</value>
    </property>
    <!--  data2  -->
    <property>
        <name>dfs.namenode.http-address.data2.nn1</name>
        <value>di-h1-nn-data2-01.h.ab1.qttsite.net:50070</value>
    </property>
    <property>
        <name>dfs.namenode.http-address.data2.nn2</name>
        <value>di-h1-nn-data2-02.h.ab1.qttsite.net:50070</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.data2.nn1</name>
        <value>di-h1-nn-data2-01.h.ab1.qttsite.net:8020</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.data2.nn2</name>
        <value>di-h1-nn-data2-02.h.ab1.qttsite.net:8020</value>
    </property>
    <property>
        <name>dfs.namenode.servicerpc-address.data2.nn1</name>
        <value>di-h1-nn-data2-01.h.ab1.qttsite.net:8021</value>
    </property>
    <property>
        <name>dfs.namenode.servicerpc-address.data2.nn2</name>
        <value>di-h1-nn-data2-02.h.ab1.qttsite.net:8021</value>
    </property>
    <property>
        <name>dfs.client.failover.proxy.provider.data2</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
    </property>
    <!--  flink-2  -->
    <property>
        <name>dfs.ha.namenodes.flink-2</name>
        <value>nn1,nn2</value>
    </property>
    <property>
        <name>dfs.namenode.http-address.flink-2.nn2</name>
        <value>emr-header-2.cluster-123446:50070</value>
    </property>
    <property>
        <name>dfs.namenode.http-address.flink-2.nn1</name>
        <value>emr-header-1.cluster-123446:50070</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.flink-2.nn2</name>
        <value>emr-header-2.cluster-123446:8020</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.flink-2.nn1</name>
        <value>emr-header-1.cluster-123446:8020</value>
    </property>
    <property>
        <name>dfs.namenode.servicerpc-address.flink-2.nn2</name>
        <value>emr-header-2.cluster-123446:8021</value>
    </property>
    <property>
        <name>dfs.namenode.servicerpc-address.flink-2.nn1</name>
        <value>emr-header-1.cluster-123446:8021</value>
    </property>
    <property>
        <name>dfs.client.failover.proxy.provider.flink-2</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
    </property>
    <!--  pub1  -->
    <property>
        <name>dfs.ha.namenodes.pub1</name>
        <value>nn1,nn2</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.pub1.nn1</name>
        <value>di-h1-nn-pub1-01.h.ab1.qttsite.net:8020</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.pub1.nn2</name>
        <value>di-h1-nn-pub1-02.h.ab1.qttsite.net:8020</value>
    </property>
    <property>
        <name>dfs.client.failover.proxy.provider.pub1</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
    </property>
    <!--rt2-->
    <property>
        <name>dfs.ha.namenodes.rt2</name>
        <value>nn1,nn2</value>
    </property>
    <property>
        <name>dfs.namenode.servicerpc-address.rt2.nn1</name>
        <value>di-h4-nn-01.h.ab1.qttsite.net:8021</value>
    </property>
    <property>
        <name>dfs.namenode.servicerpc-address.rt2.nn2</name>
        <value>di-h4-nn-02.h.ab1.qttsite.net:8021</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.rt2.nn1</name>
        <value>di-h4-nn-01.h.ab1.qttsite.net:8020</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.rt2.nn2</name>
        <value>di-h4-nn-02.h.ab1.qttsite.net:8020</value>
    </property>
    <property>
        <name>dfs.namenode.http-address.rt2.nn1</name>
        <value>di-h4-nn-01.h.ab1.qttsite.net:50070</value>
    </property>
    <property>
        <name>dfs.namenode.http-address.rt2.nn2</name>
        <value>di-h4-nn-02.h.ab1.qttsite.net:50070</value>
    </property>
    <property>
        <name>dfs.client.failover.proxy.provider.rt2</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
    </property>
    <!--  others  -->
    <property>
        <name>dfs.client.socket-timeout</name>
        <value>120000</value>
        <final>true</final>
    </property>
    <property>
        <name>fs.permissions.umask-mode</name>
        <value>022</value>
        <final>true</final>
    </property>
    <!--    增加写入重试次数-->
    <property>
        <name>dfs.client.block.write.locateFollowingBlock.retries</name>
        <value>10</value>
        <final>true</final>
    </property>
    <!--    副本数-->
    <property>
        <name>dfs.replication</name>
        <value>3</value>
        <final>true</final>
    </property>
</configuration>